######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 27 15:02:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += main.hh netsocket.hh hotrumor.hh quorum.hh
SOURCES += main.cc netsocket.cc hotrumor.cc quorum.cc
